# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HourModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Your first name.', max_length=15)),
                ('last_name', models.CharField(help_text='Your last name.', max_length=20)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('reason', models.CharField(help_text='The reason you need this shift covered.', max_length=250)),
            ],
        ),
    ]
