# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 04:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hour_manager', '0002_auto_20170527_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='cover_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_username', models.CharField(max_length=25)),
                ('poster_first', models.CharField(max_length=25)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='suggestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='hour_history',
            name='cover_first',
        ),
        migrations.RemoveField(
            model_name='hour_history',
            name='cover_last',
        ),
        migrations.AddField(
            model_name='hour_history',
            name='cover_username',
            field=models.CharField(default=django.utils.timezone.now, max_length=25),
            preserve_default=False,
        ),
    ]
